name: Go CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: golang-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run tests
      run: go test ./frontend
      #anything
