name: Build

on: [push]

jobs:
  build:

    runs-on: golang:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: kjumbe
        password: sillypassword
      
    - name: Build and push Docker Compose
      run: |
        docker-compose build
        # Optionally push if you have services defined with "image" and want to push them:
        # docker-compose push

